# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Asciinema2video < Formula
  desc "Convert asciinema recordings to video"
  homepage "https://github.com/spagu/asciinema2video"
  version "1.0.1"
  license "BSD-3-Clause"

  depends_on "ffmpeg"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/spagu/asciinema2video/releases/download/v1.0.1/asciinema2video_1.0.1_darwin_amd64.tar.gz"
      sha256 "6fd6f79f21d5e569e3af973202ee94223fd3d7941e669fdbe127363b30775fff"

      define_method(:install) do
        bin.install "asciinema2video"
        man1.install "man/asciinema2video.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/spagu/asciinema2video/releases/download/v1.0.1/asciinema2video_1.0.1_darwin_arm64.tar.gz"
      sha256 "4220cc21b40c42f828dc8a555b68eac0f3cf75aab9eed4974190db6ed8c533db"

      define_method(:install) do
        bin.install "asciinema2video"
        man1.install "man/asciinema2video.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/spagu/asciinema2video/releases/download/v1.0.1/asciinema2video_1.0.1_linux_amd64.tar.gz"
      sha256 "55e040cb5c51d3de0b0378ee607e59a42d52c0ed67695a9318efc6f09f79247a"
      define_method(:install) do
        bin.install "asciinema2video"
        man1.install "man/asciinema2video.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/spagu/asciinema2video/releases/download/v1.0.1/asciinema2video_1.0.1_linux_arm64.tar.gz"
      sha256 "47512351d7625d2d42008f211d15bba50d5843ee1e115b44f6522230b0025af8"
      define_method(:install) do
        bin.install "asciinema2video"
        man1.install "man/asciinema2video.1"
      end
    end
  end

  test do
    system "#{bin}/asciinema2video", "--version"
  end
end
