# Homebrew formula for SSG - Static Site Generator
# Install: brew install spagu/tap/ssg
# Or: brew tap spagu/tap && brew install ssg
#
# Generated by .github/workflows/homebrew.yml — do not edit by hand.

class Ssg < Formula
  desc "Fast static site generator written in Go"
  homepage "https://github.com/spagu/ssg"
  version "1.8.42"
  license "BSD-3-Clause"

  on_macos do
    on_arm do
      url "https://github.com/spagu/ssg/releases/download/v1.8.42/ssg-darwin-arm64.tar.gz"
      sha256 "8b39f58a8a21bf4f6d303517ae0d670e1b6b1165513083c2706d3c8c44042f87"
    end
    on_intel do
      url "https://github.com/spagu/ssg/releases/download/v1.8.42/ssg-darwin-amd64.tar.gz"
      sha256 "4f7904f35d3af9720759591057ae3364cd9acc10790943546810d3848a5fae1f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/spagu/ssg/releases/download/v1.8.42/ssg-linux-arm64.tar.gz"
      sha256 "2ada766d4538d3ff31f3bdae1b184f0e676f0b341535b0676b6805330f6c3ec9"
    end
    on_intel do
      url "https://github.com/spagu/ssg/releases/download/v1.8.42/ssg-linux-amd64.tar.gz"
      sha256 "51aa0dd73c09b384111f23100e2d22d08400c0e5d634d4c3772bbe993d7bd577"
    end
  end

  def install
    bin.install "ssg"
  end

  test do
    system "#{bin}/ssg", "--help"
  end
end
